DeOnibusTest/DeOnibusTest/Models/ErrorViewModel.cs
using System;

namespace DeOnibusTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeOnibusTest/DeOnibusTest/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DeOnibusTest.Domain.ValueObjects;
using DeOnibusTest.Domain.Interfaces;
using DeOnibusTest.Domain.Entities;
using System.Linq;

namespace DeOnibusTest.Controllers
{
    public class HomeController : Controller
    {

        public HomeController()
        {          
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

DeOnibusTest/DeOnibusTest/Controllers/TripController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DeOnibusTest.Domain.ValueObjects;
using DeOnibusTest.Domain.Interfaces;
using DeOnibusTest.Domain.Entities;
using System.Linq;

namespace DeOnibusTest.Controllers
{
    public class TripController : Controller
    {

        private readonly Service.Services.FavoriteTrips _favoriteTrips;

        public TripController(IRepository repository)
        {
            _favoriteTrips = new Service.Services.FavoriteTrips(repository);
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Classes = await Service.Services.ConsumeAPI.GetClasses();
            return View();
        }

        public async Task<ActionResult> GetTrips(List<string> Classes, int Departure, decimal MaxPrice)
        {
            List<Trips> trips = await Service.Services.ConsumeAPI.GetTrips(Classes, Departure, MaxPrice);
            List<string> favoriteTripsIds = await _favoriteTrips.GetFavoriteTripsIds();

            trips = trips.Where(x => !favoriteTripsIds.Contains(x.ObjectId)).ToList();

            return PartialView("_Trips", trips);
        }

        public async Task<ActionResult> GetFavoriteTrips()
        {
            List<Trips> trips = await Service.Services.ConsumeAPI.GetTrips(null, 0, 0);
            List<string> favoriteTripsIds = await _favoriteTrips.GetFavoriteTripsIds();

            trips = trips.Where(x => favoriteTripsIds.Contains(x.ObjectId)).ToList();

            return PartialView("_FavoriteTrips", trips);
        }

        public ActionResult SaveFavoriteTrips(List<string> SelectedTrips)
        {
            try
            {
                foreach (var trip in SelectedTrips)
                {
                    _favoriteTrips.SaveOrUpdate(new FavoriteTrip() { TripId = trip });
                }
                return Ok();
            }
            catch (System.Exception ex)
            {
                return Problem(detail: ex.Message, title: "Erro");
            }
        }

        public async Task<ActionResult> RemoveFavoriteTrips(string TripId)
        {
            try
            {
                var favorite = await _favoriteTrips.GetByTripId(TripId);
                _favoriteTrips.Delete(favorite);
                return Ok();
            }
            catch (System.Exception ex)
            {
                return Problem(detail: ex.Message, title: "Erro");
            } 
        }

    }
}

DeOnibusTest/DeOnibusTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

DeOnibusTest/DeOnibusTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeOnibusTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/select2/dist/css/select2.css" rel="stylesheet" />
    <link href="~/lib/select2/dist/css/select2-custom.css" rel="stylesheet" />
    <link href="~/lib/sweetalert/dist/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Trip" asp-action="Index">deônibus</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Maicon Ghidolin
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/dist/js/select2.js"></script>
    <script src="~/lib/sweetalert/dist/sweetalert2.min.js"></script>
    <script src="~/js/alerts.js"></script>
    <script src="~/js/ajax.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

DeOnibusTest/DeOnibusTest/Views/Trip/Index.cshtml
@model List<DeOnibusTest.Domain.ValueObjects.Trips>

@{
    ViewData["Title"] = "Trips";
    List<string> classes = ViewBag.Classes;
}

<input type="hidden" id="hddSelectedTrips" value="" />

<div class="row">
    <div class="col-md-12 col-lg-8">

        <div class="card w-100 card-trip">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Classes</label>
                            <select id="selFilterClasses" class="form-control select2" multiple asp-items="Html.GetSelectList(classes)"></select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Saída</label>
                            <select id="selFilterDeparture" class="form-control select2">
                                <option value="">Selecione</option>
                                <option value="1">Madrugada</option>
                                <option value="2">Manhã</option>
                                <option value="3">Tarde</option>
                                <option value="4">Noite</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label" for="txtMaxPrice">Preço máximo</label>
                            <input type="text" id="txtMaxPrice" placeholder="Digite..." class="form-control">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="divTrips"></div>

    </div>
    <div class="col-md-12 col-lg-4">
        <div id="divFavoriteTrips"></div>
    </div>
</div>
<div class="row" id="divBtnFavoriteTrips" style="display:none">
    <div class="col-sm-12">
        <button class="btn btn-sm btn-success" onclick="SaveFavoriteTrips()">Confirmar favoritos</button>
    </div>
</div>

@section Scripts {
    <script src="~/js/Trips/trips.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $(".select2").select2();

            $("#selFilterClasses,#selFilterDeparture,#txtMaxPrice").change(function () {
                GetTrips();
            });

            GetTrips();
            GetFavoriteTrips();
        });

    </script>

}

DeOnibusTest/DeOnibusTest/Views/Trip/_FavoriteTrips.cshtml
@model List<DeOnibusTest.Domain.ValueObjects.Trips>
@using DeOnibusTest.Domain.Extensions

@if (Model.IsNotNullOrEmpty())
{

    <div class="card text-center w-100 card-trip">
        <div class="card-body">
            <h5 class="card-title">Viagens favoritas</h5>
            <p class="card-text text-muted" style="font-size: 14px;">Horários ônibus e preços de passagens</p>
        </div>
    </div>

    foreach (var trip in Model)
    {
        <div class="card w-100 card-trip">
            <div class="card-body">

                <div class="row">
                    <div class="col-sm-12 card-trip-company">
                        <p class="card-text">@trip.Company.Name</p>
                    </div>
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-8 card-trip-date">
                                <p class="card-text">@trip.DepartureDate.Iso.ToString("HH:mm") <i class="fas fa-long-arrow-alt-right"></i> <span class="text-muted">@trip.ArrivalDate.Iso.ToString("HH:mm")</span></p>
                            </div>
                            <div class="col-sm-4 card-trip-price">
                                <p class="card-text">R$ @trip.Price.ToString("N")</p>
                                <span class="card-text text-muted">+ taxas</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 card-trip-city">
                                <p class="card-text"><span class="text-muted">de </span> @trip.Origin</p>
                                <p class="card-text"><span class="text-muted">para </span> @trip.Destination</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-8 card-trip-busclass">
                                <p class="card-text">@trip.BusClass</p>
                            </div>
                            <div class="col-sm-12 col-md-4 text-right">
                                <button class="btn btn-sm btn-danger" onclick="RemoveFavoriteTrip('@trip.ObjectId')">Remover</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="card text-center w-100 card-trip">
        <div class="card-body">
            <h5 class="card-title">Sem viagens favoritas</h5>
        </div>
    </div>
}

DeOnibusTest/DeOnibusTest/Views/Trip/_Trips.cshtml
@model List<DeOnibusTest.Domain.ValueObjects.Trips>
@using DeOnibusTest.Domain.Extensions

@if (Model.IsNotNullOrEmpty())
{

    <div class="card text-center w-100 card-trip">
        <div class="card-body">
            <h5 class="card-title">IDA</h5>
            <p class="card-text" style="margin-bottom: 10px">@Model.First().DepartureDate.Iso.ToString("ddd, dd 'de' MMMM yyyy")</p>
            <p class="card-text" style="font-weight: 500;font-size: 17px;">Passagem de ônibus de @Model.First().Origin para @Model.First().Destination </p>
            <p class="card-text text-muted" style="font-size: 14px;">Horários ônibus e preços de passagens</p>
        </div>
    </div>

    foreach (var trip in Model)
    {
        <div class="card w-100 card-trip">
            <div class="card-body">

                <div class="row">
                    <div class="col-sm-12 col-lg-3 card-trip-company">
                        <p class="card-text">@trip.Company.Name</p>
                    </div>
                    <div class="col-sm-12 col-lg-9">
                        @if (trip.BetterPrice)
                        {
                            <div class="row">
                                <div class="col-sm-12 text-right" style=" color: #fff; font-size: 17px; font-weight: 500; background-color: #008A5D;">
                                    <p class="card-text">Melhor preço</p>
                                </div>
                            </div>
                        }
                        <div class="row">
                            <div class="col-sm-8 card-trip-date">
                                <p class="card-text">@trip.DepartureDate.Iso.ToString("HH:mm") <i class="fas fa-long-arrow-alt-right"></i> <span class="text-muted">@trip.ArrivalDate.Iso.ToString("HH:mm")</span></p>
                            </div>
                            <div class="col-sm-4 card-trip-price">
                                <p class="card-text">R$ @trip.Price.ToString("N")</p>
                                <span class="card-text text-muted">+ taxas</span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 card-trip-city">
                                <p class="card-text"><span class="text-muted">de </span> @trip.Origin</p>
                                <p class="card-text"><span class="text-muted">para </span> @trip.Destination</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-8 card-trip-busclass">
                                <p class="card-text">@trip.BusClass</p>
                            </div>
                            <div class="col-sm-12 col-md-4 text-right">
                                <button class="btn btn-sm btn-success" onclick="SelectTrip(this, '@trip.ObjectId')">Selecionar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="card text-center w-100 card-trip">
        <div class="card-body">
            <h5 class="card-title">Sem passagens disponíveis</h5>
        </div>
    </div>
}